[package]
name = "adapter"
version = "1.0.0"
authors = ["Arash Hatami <hatamiarash7@gmail.com>"]
edition = "2018"

[lib]
name = "adapter"
crate-type = ["staticlib"]

[dependencies]
lorenz = { path = "../core" }
